name: MkDocs CI/CD
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      # - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@9.4.8-insiders-4.43.0
      - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material.git@9.6.12
      # mkdocs-material-9.6.12
      - run: pip install mkdocs-literate-nav
      - run: pip install mkdocs-section-index
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-video
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-print-site-plugin
      p run: pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python pymdown-extensions
      - run: mkdocs gh-deploy --force
